source=hook.c bgp.c attrs.c packets.c br_hasht.c brc_memory.c br_string.c brc_net_io.c br_ea.c br_proto.c br_net_proto.c msg_relay.c br_irc.c br_main.c
root-rel=../../
dir-name=proto/bgp

include ../../Rules
